-- 启用 pgvector 扩展
create extension if not exists vector;

-- 验证扩展已启用
select extname from pg_extension where extname = 'vector';

-- 用户表（Spring JPA ddl-auto=update 会自动创建，这里显式定义确保一致性）
create table if not exists users (
    id bigint generated by default as identity primary key,
    username varchar(64) not null unique,
    password_hash varchar(255) not null,
    email varchar(128) unique,
    created_at timestamp default current_timestamp
);

-- 面试会话表
create table if not exists interview_session (
    id bigint generated by default as identity primary key,
    session_id varchar(64) not null unique,
    user_id varchar(64) not null,
    job_description text,
    resume_id bigint,
    status varchar(20),
    created_at timestamp default current_timestamp
);

-- 面试题目表
create table if not exists interview_question (
    id bigint generated by default as identity primary key,
    session_id varchar(