package com.example.interview.service.job;

import org.springframework.stereotype.Component;

import java.time.LocalDate;
import java.util.List;

/**
 * 内置多频道精选数据源（v1.26.0）
 *
 * 与 SeedCampusJobProvider（秋招专场）互补，覆盖：
 * - SPRING 春招（2027 届春季补招）
 * - SOCIAL 社招（各行业社招，含经验要求分层）
 * - INTERN 实习（日常实习/暑期实习）
 * - TARGETED 定向专项（选调生/国企专项/地方专项引才计划）
 *
 * 行业覆盖：互联网/金融/教育/医疗/快消/游戏/汽车/物流/咨询/传媒/能源/制造/通信等。
 * 每次刷新幂等 upsert，截止日期过期后由 JobAgentService 自动下架。
 */
@Component
public class SeedMultiChannelJobProvider implements JobPlatformAdapter {

    private static final String SPRING = "SPRING";
    private static final String SOCIAL = "SOCIAL";
    private static final String INTERN = "INTERN";
    private static final String TARGETED = "TARGETED";

    @Override
    public String platform() {
        return "精选频道";
    }

    @Override
    public List<JobDto> fetch() {
        return List.of(
                // ── SPRING 春招 ──
                new JobDto("seed-multi-kuaishou-spring", "2027 届春季校园招聘·技术类（后端/客户端/算法）", "快手",
                        "互联网", "技术", "北京/杭州", "25k-45k·15薪",
                        "本科及以上", "2027 届应届毕业生", SPRING, LocalDate.of(2027, 3, 31),
                        "https://zhaopin.kuaishou.cn/campus",
                        "快手春季校园招聘，参与短视频、直播、本地生活等核心业务研发，含可灵大模型方向。",
                        "1. 本科及以上学历，计算机相关专业优先；2. 熟悉 Java/Go/C++ 任一语言；3. 有实习或项目经验者优先。",
                        "春招,技术,短视频,大厂"),
                new JobDto("seed-multi-youdao-spring", "2027 届春季校园招聘·产品/教研/技术", "网易有道",
                        "教育", "产品", "杭州/北京", "15k-28k·14薪",
                        "本科及以上", "2027 届应届毕业生", SPRING, LocalDate.of(2027, 3, 20),
                        "https://campus.163.com/app/index",
                        "有道春季校招覆盖 AI 学习硬件、智能辅导、成人教育等业务，教育+技术复合培养。",
                        "1. 本科及以上学历，专业不限；2. 对教育行业有热情；3. 技术岗需编程基础，教研岗需学科功底。",
                        "春招,教育,AI学习,产品"),
                new JobDto("seed-multi-mengniu-spring", "2027 届春季校园招聘·管理培训生（管培生计划）", "蒙牛",
                        "快消", "职能", "呼和浩特/北京/上海", "10k-16k·13薪",
                        "本科及以上", "2027 届应届毕业生", SPRING, LocalDate.of(2027, 4, 15),
                        "https://campus.mengniu.cn/",
                        "蒙牛管理培训生计划，轮岗覆盖品牌市场、供应链、销售管理，纳入集团青年人才培养梯队。",
                        "1. 本科及以上学历，专业不限；2. 接受全国轮岗与驻外；3. 沟通协调能力强。",
                        "春招,快消,管培生,轮岗"),
                new JobDto("seed-multi-hengrui-spring", "2027 届春季校园招聘·医药研发/临床监察", "恒瑞医药",
                        "医疗", "技术", "连云港/上海/成都", "12k-22k·14薪",
                        "硕士优先", "2027 届应届毕业生", SPRING, LocalDate.of(2027, 4, 10),
                        "https://careers.hrs.com.cn/",
                        "恒瑞医药春季校招，参与创新药研发、临床试验、注册申报等方向，创新药管线行业领先。",
                        "1. 药学/化学/临床医学等相关专业硕士及以上优先；2. 了解 GCP/GMP 者优先；3. 有实验室科研经历。",
                        "春招,医药,研发,创新药"),
                new JobDto("seed-multi-geely-spring", "2027 届春季校园招聘·整车研发/智能驾驶", "吉利汽车",
                        "汽车", "技术", "杭州/宁波/西安", "14k-26k·14薪",
                        "本科及以上", "2027 届应届毕业生", SPRING, LocalDate.of(2027, 4, 20),
                        "https://zhaopin.geely.com/campus",
                        "吉利汽车春季校招，覆盖整车研发、三电系统、智能驾驶、全球化品牌等方向。",
                        "1. 车辆工程/电气/计算机等相关专业本科及以上；2. 熟悉 C/C++ 或汽车电子者优先；3. 认同工程师文化。",
                        "春招,汽车,智能驾驶,新能源"),
                new JobDto("seed-multi-mihoyo-spring", "2027 届春季校园招聘·技术/美术/游戏策划", "米哈游",
                        "游戏", "综合", "上海", "20k-40k·14薪",
                        "本科及以上", "2027 届应届毕业生", SPRING, LocalDate.of(2027, 3, 15),
                        "https://jobs.mihoyo.com/#campus",
                        "米哈游春季校招，参与原神、崩坏系列及新项目研发，技术美术与原创 IP 团队招募。",
                        "1. 本科及以上学历；2. 技术岗需扎实的编程或图形学基础；3. 美术岗需作品集；4. 热爱游戏。",
                        "春招,游戏,二次元,原创IP"),
                new JobDto("seed-multi-sf-spring", "2027 届春季校园招聘·管培生/数字化研发", "顺丰速运",
                        "物流", "综合", "深圳/北京/成都", "12k-22k·13薪",
                        "本科及以上", "2027 届应届毕业生", SPRING, LocalDate.of(2027, 4, 30),
                        "https://careers.sf-express.com/campus",
                        "顺丰春季校招，覆盖物流科技、供应链数字化、航空运营等方向，管培生双通道发展。",
                        "1. 本科及以上学历，物流/计算机/供应链相关专业优先；2. 接受轮岗与一线历练。",
                        "春招,物流,供应链,数字化"),
                new JobDto("seed-multi-deloitte-spring", "2027 届春季校园招聘·审计/咨询/税务", "德勤",
                        "咨询", "金融", "北京/上海/广州/深圳", "11k-18k·13薪",
                        "本科及以上", "2027 届应届毕业生", SPRING, LocalDate.of(2027, 3, 31),
                        "https://www2.deloitte.com/cn/careers",
                        "德勤春季校招（Deloitte Club 补录），参与审计与鉴证、管理咨询、数字化转型项目。",
                        "1. 会计/金融/计算机等相关专业；2. 通过 CPA 部分科目者优先；3. 英语流利，抗压能力强。",
                        "春招,四大,咨询,审计"),
                new JobDto("seed-multi-nio-spring", "2027 届春季校园招聘·整车软件/用户运营", "蔚来",
                        "汽车", "技术", "上海/合肥", "16k-30k·14薪",
                        "本科及以上", "2027 届应届毕业生", SPRING, LocalDate.of(2027, 4, 15),
                        "https://nio.com/careers/campus",
                        "蔚来春季校招，参与智能座舱、换电网络、社区运营等方向，用户企业文化的开创者。",
                        "1. 本科及以上学历；2. 技术/设计岗需相关专业背景与作品；3. 认同用户型企业理念。",
                        "春招,新能源汽车,智能座舱"),
                new JobDto("seed-multi-mgtv-spring", "2027 届春季校园招聘·内容制作/技术研发", "芒果超媒",
                        "传媒", "综合", "长沙/北京", "10k-20k·13薪",
                        "本科及以上", "2027 届应届毕业生", SPRING, LocalDate.of(2027, 4, 20),
                        "https://careers.hunantv.com/",
                        "芒果超媒春季校招，参与综艺内容制作、芒果 TV 客户端研发、AI 内容生产等方向。",
                        "1. 本科及以上学历，传媒/计算机相关专业优先；2. 内容岗需提交作品；3. 热爱视听行业。",
                        "春招,传媒,综艺,内容"),

                // ── SOCIAL 社招 ──
                new JobDto("seed-multi-huawei-cloud-social", "社招·云核心网研发工程师", "华为",
                        "通信", "技术", "深圳/东莞/成都", "30k-60k·14-16薪",
                        "本科及以上", "3-5 年", SOCIAL, null,
                        "https://career.huawei.com/",
                        "华为云核心网团队社招，参与 5G-A/6G 核心网、云化网络架构研发，全球化项目机会。",
                        "1. 3 年以上电信/云计算开发经验；2. 精通 Java/C++/Go 任一语言；3. 熟悉网络协议与分布式架构。",
                        "社招,通信,云计算,高薪"),
                new JobDto("seed-multi-pingan-social", "社招·Java 高级开发工程师", "平安科技",
                        "金融", "技术", "上海/深圳", "25k-40k·14薪",
                        "本科及以上", "1-3 年", SOCIAL, LocalDate.of(2026, 12, 31),
                        "https://careers.pingan.com/",
                        "平安科技社招，参与金融核心系统、AI 中台建设，技术栈前沿，晋升通道清晰。",
                        "1. 1 年以上 Java 开发经验；2. 熟悉 Spring Cloud、MySQL、Redis；3. 有金融行业经验者优先。",
                        "社招,金融科技,Java,中台"),
                new JobDto("seed-multi-bytedance-da-social", "社招·数据分析师（增长方向）", "字节跳动",
                        "互联网", "技术", "北京/上海", "25k-45k·15薪",
                        "本科及以上", "1-3 年", SOCIAL, null,
                        "https://jobs.bytedance.com/",
                        "字节跳动增长团队社招，负责抖音/今日头条增长策略分析、AB 实验设计与归因建模。",
                        "1. 1 年以上数据分析经验；2. 精通 SQL/Python，熟悉因果推断与 A/B 实验；3. 有大厂增长经验优先。",
                        "社招,数据分析,增长,大厂"),
                new JobDto("seed-multi-jdwl-social", "社招·仓储运营管理岗", "京东物流",
                        "物流", "运营", "全国多地", "8k-15k·13薪",
                        "大专及以上", "经验不限", SOCIAL, LocalDate.of(2026, 12, 31),
                        "https://zhaopin.jdwl.com/",
                        "京东物流仓储运营社招，负责仓内作业管理、效率优化与团队建设，管理序列发展。",
                        "1. 大专及以上学历，专业不限；2. 接受倒班与全国分配；3. 有仓储/供应链经验者优先。",
                        "社招,物流,运营,门槛友好"),
                new JobDto("seed-multi-xdf-social", "社招·高中教研主讲教师", "新东方",
                        "教育", "其他", "北京/线上", "15k-30k·13薪",
                        "本科及以上", "1-3 年", SOCIAL, null,
                        "https://zhaopin.xdf.cn/",
                        "新东方高中业务教研主讲社招，负责课程研发与在线授课，学科顶尖讲师培养体系。",
                        "1. 1 年以上教学经验，学科功底扎实；2. 普通话标准，表达能力强；3. 有在线大班课经验者优先。",
                        "社招,教育,教师,在线教育"),
                new JobDto("seed-multi-mindray-social", "社招·医疗器械注册专员", "迈瑞医疗",
                        "医疗", "其他", "深圳", "12k-20k·14薪",
                        "本科及以上", "3-5 年", SOCIAL, LocalDate.of(2027, 1, 31),
                        "https://careers.mindray.com/",
                        "迈瑞医疗注册事务社招，负责监护/影像产品线的 NMPA 与海外注册申报。",
                        "1. 3 年以上医疗器械注册经验；2. 熟悉 NMPA/FDA/CE 法规体系；3. 生物医学/药学相关专业。",
                        "社招,医疗器械,注册,法规"),
                new JobDto("seed-multi-pg-social", "社招·品牌市场经理", "宝洁",
                        "快消", "市场", "广州", "20k-35k·14薪",
                        "本科及以上", "3-5 年", SOCIAL, LocalDate.of(2027, 2, 28),
                        "https://www.pgcareers.com.cn/",
                        "宝洁品牌管理社招，负责品牌年度生意规划、媒介投放与新品上市，品牌经理人摇篮。",
                        "1. 3 年以上快消/市场经验；2. 数据驱动，熟悉媒介与消费者洞察；3. 英语流利。",
                        "社招,快消,品牌,市场"),
                new JobDto("seed-multi-citic-social", "社招·行业研究员（TMT 方向）", "中信证券",
                        "金融", "金融", "北京/上海", "25k-50k·14薪",
                        "硕士及以上", "3-5 年", SOCIAL, LocalDate.of(2027, 1, 31),
                        "https://careers.citics.com/",
                        "中信证券研究所社招，负责 TMT 行业深度研究与买方服务，头部卖方平台。",
                        "1. 3 年以上卖方/买方研究经验；2. 财务建模功底扎实；3. 有 CPA/CFA 者优先。",
                        "社招,证券,研究员,卖方"),
                new JobDto("seed-multi-xpeng-social", "社招·自动驾驶感知算法工程师", "小鹏汽车",
                        "汽车", "技术", "广州/上海", "35k-60k·15薪",
                        "硕士及以上", "3-5 年", SOCIAL, null,
                        "https://job.xiaopeng.com/",
                        "小鹏自动驾驶中心社招，负责 BEV 感知、占用网络、端到端模型研发与量产落地。",
                        "1. 3 年以上自动驾驶感知算法经验；2. 精通 PyTorch 与 CUDA 优化；3. 有量产项目经验优先。",
                        "社招,自动驾驶,算法,新能源车"),
                new JobDto("seed-multi-accenture-social", "社招·数字化转型咨询顾问", "埃森哲",
                        "咨询", "其他", "上海/北京/大连", "15k-30k·13薪",
                        "本科及以上", "1-3 年", SOCIAL, LocalDate.of(2027, 3, 31),
                        "https://www.accenture.com/cn-en/careers",
                        "埃森哲咨询社招，参与大型企业数字化转型的业务蓝图设计与系统落地，全球化项目。",
                        "1. 1 年以上咨询/IT 实施经验；2. 熟悉 ERP/数据中台任一领域；3. 英语可作为工作语言。",
                        "社招,咨询,数字化,外企"),
                new JobDto("seed-multi-vanke-social", "社招·商业项目营销策划", "万科",
                        "其他", "市场", "深圳/上海/武汉", "12k-22k·13薪",
                        "本科及以上", "1-3 年", SOCIAL, LocalDate.of(2026, 12, 31),
                        "https://careers.vanke.com/",
                        "万科商业开发与运营社招，负责购物中心招商推广与营销活动策划。",
                        "1. 1 年以上商业地产/零售营销经验；2. 活动策划与文案能力强；3. 接受项目驻场。",
                        "社招,地产,营销,商业"),
                new JobDto("seed-multi-chinamobile-social", "社招·网络运维工程师", "中国移动",
                        "通信", "技术", "全国各省", "9k-16k·13薪",
                        "本科及以上", "经验不限", SOCIAL, LocalDate.of(2027, 3, 31),
                        "https://job.10086.cn/social",
                        "中国移动省公司网络运维社招，负责核心网/传输网/政企专网维护与优化。",
                        "1. 本科及以上学历，通信/计算机相关专业；2. 熟悉数通设备与网络协议；3. 接受值班备勤。",
                        "社招,运营商,国企,稳定"),

                // ── INTERN 实习 ──
                new JobDto("seed-multi-tencent-intern", "日常实习·后端开发工程师", "腾讯",
                        "互联网", "技术", "深圳/北京", "6k-9k·月",
                        "本科及以上", "在校生", INTERN, LocalDate.of(2026, 12, 31),
                        "https://join.qq.com/post.php?posttype=2",
                        "腾讯日常实习，参与微信/腾讯云/游戏等业务后端研发，表现优秀可转 2027 秋招绿通。",
                        "1. 本科及以上在读，一周实习 4 天以上、持续 3 个月以上；2. 熟悉 Java/Go 任一语言；3. 有项目经验。",
                        "实习,后端,大厂,转正绿通"),
                new JobDto("seed-multi-aliyun-intern", "日常实习·AI 产品经理", "阿里云",
                        "互联网", "产品", "杭州/北京", "6k-9k·月",
                        "本科及以上", "在校生", INTERN, LocalDate.of(2026, 12, 15),
                        "https://talent.alibaba.com/campus/position-list",
                        "阿里云 AI 产品实习，参与通义大模型产品需求分析与落地，导师一对一带教。",
                        "1. 本科及以上在读；2. 对大模型/云计算有认知；3. 逻辑清晰，文档能力强。",
                        "实习,产品,大模型,云计算"),
                new JobDto("seed-multi-meituan-intern", "日常实习·机器学习算法", "美团",
                        "互联网", "技术", "北京/上海", "7k-10k·月",
                        "硕士在读", "在校生", INTERN, LocalDate.of(2026, 11, 30),
                        "https://zhaopin.meituan.com/web/campus",
                        "美团算法实习，参与配送路径优化、搜索排序或大模型应用研发，真实业务场景海量数据。",
                        "1. 硕士在读，计算机/数学相关专业；2. 熟悉 PyTorch，有论文或竞赛经历优先；3. 实习 3 个月以上。",
                        "实习,算法,机器学习,大厂"),
                new JobDto("seed-multi-pdd-intern", "日常实习·数据分析", "拼多多",
                        "互联网", "技术", "上海", "8k-11k·月",
                        "本科及以上", "在校生", INTERN, LocalDate.of(2026, 12, 31),
                        "https://careers.pinduoduo.com/campus",
                        "拼多多数据分析实习，负责电商业务大盘监控、专项分析与策略建议，高成长高回报。",
                        "1. 本科及以上在读，统计/计算机/经济学相关专业；2. 精通 SQL 与 Excel；3. 每周实习 4 天以上。",
                        "实习,电商,数据分析,高薪"),
                new JobDto("seed-multi-kpmg-intern", "寒假实习·审计助理", "毕马威",
                        "咨询", "金融", "北京/上海/广州/深圳", "5k-7k·月",
                        "本科及以上", "在校生", INTERN, LocalDate.of(2026, 11, 15),
                        "https://kpmg.com/cn/careers",
                        "毕马威寒假实习计划（Elite 补录），参与年审项目现场工作，优秀者获校招 early offer。",
                        "1. 会计/财务相关专业大三及以上；2. 通过初级会计或 CPA 科目者优先；3. 接受出差。",
                        "实习,四大,审计,earlyoffer"),
                new JobDto("seed-multi-pfizer-intern", "日常实习·医学信息沟通", "辉瑞",
                        "医疗", "其他", "上海/北京/广州", "5k-8k·月",
                        "本科及以上", "在校生", INTERN, LocalDate.of(2026, 12, 31),
                        "https://pfizer.wd3.myworkdayjobs.com/PfizerCareers",
                        "辉瑞医学信息实习，参与产品医学资料整理与学术会议支持，外企医药管培前置。",
                        "1. 临床医学/药学相关专业在读；2. 英语六级以上；3. 沟通表达能力强。",
                        "实习,医药,外企,医学信息"),
                new JobDto("seed-multi-bytedance-fe-intern", "日常实习·前端开发工程师", "字节跳动",
                        "互联网", "技术", "北京/上海/深圳", "7k-10k·月",
                        "本科及以上", "在校生", INTERN, LocalDate.of(2026, 12, 31),
                        "https://jobs.bytedance.com/campus/position?keywords=前端",
                        "字节前端实习，参与抖音/飞书 Web 端研发，React + 现代 工程化体系，导师制培养。",
                        "1. 本科及以上在读；2. 熟悉 TypeScript/React；3. 每周实习 4 天以上、持续 3 个月以上。",
                        "实习,前端,React,大厂"),
                new JobDto("seed-multi-mihoyo-intern", "日常实习·游戏文案策划", "米哈游",
                        "游戏", "其他", "上海", "6k-9k·月",
                        "本科及以上", "在校生", INTERN, LocalDate.of(2026, 12, 15),
                        "https://jobs.mihoyo.com/#intern",
                        "米哈游文案策划实习，参与世界观构建、剧情文本与角色塑造，原创 IP 项目机会。",
                        "1. 本科及以上在读，中文/文学相关专业优先；2. 深度热爱二次元游戏；3. 需提交文字作品。",
                        "实习,游戏,文案,二次元"),
                new JobDto("seed-multi-anta-intern", "日常实习·电商运营", "安踏",
                        "快消", "运营", "厦门", "4.5k-7k·月",
                        "本科及以上", "在校生", INTERN, LocalDate.of(2026, 11, 30),
                        "https://anta-campus.zhiye.com/",
                        "安踏集团电商实习，参与天猫/抖音旗舰店运营与大促操盘，多品牌集团历练。",
                        "1. 本科及以上在读，专业不限；2. 熟悉主流电商平台玩法；3. 数据敏感度高。",
                        "实习,快消,电商,运动品牌"),
                new JobDto("seed-multi-iflytek-intern", "日常实习·NLP 算法", "科大讯飞",
                        "互联网", "技术", "合肥/北京", "6k-9k·月",
                        "硕士在读", "在校生", INTERN, LocalDate.of(2026, 12, 31),
                        "https://campus.iflytek.com/",
                        "讯飞研究院 NLP 实习，参与星火大模型训练与评测、意图理解与生成任务优化。",
                        "1. 硕士在读，NLP/机器学习方向；2. 熟悉预训练模型微调与 RAG；3. 有论文者优先。",
                        "实习,大模型,NLP,人工智能"),

                // ── TARGETED 定向专项 ──
                new JobDto("seed-multi-gd-xuandiao", "2027 届定向选调生（广东省党政机关）", "中共广东省委组织部",
                        "其他", "职能", "广东省各地市", "8k-15k·13薪",
                        "本科及以上", "2027 届应届毕业生", TARGETED, LocalDate.of(2026, 10, 31),
                        "https://www.gdzz.cn/",
                        "广东省定向选调面向双一流高校应届生，录用后安排到省市直机关岗位，基层锻炼两年。",
                        "1. 双一流建设高校 2027 届全日制本科及以上；2. 中共党员（含预备）优先；3. 通过公务员录用体检标准。",
                        "定向,选调生,公务员,编制"),
                new JobDto("seed-multi-spict-targeted", "专项招聘·绿色能源青年英才计划", "国家电力投资集团",
                        "能源", "技术", "北京/上海/全国基地", "12k-22k·13薪",
                        "本科及以上", "2027 届应届毕业生", TARGETED, LocalDate.of(2026, 11, 30),
                        "https://zhaopin.spic.com.cn/",
                        "国家电投专项计划，定向培养核电、光伏、氢能方向青年技术骨干，系统内导师带培。",
                        "1. 电气/能源/核工程相关专业 2027 届毕业生；2. 愿意投身国家能源事业；3. 接受基地驻派。",
                        "定向,国企,新能源,核电"),
                new JobDto("seed-multi-asc-targeted", "专项招聘·国防科技英才计划", "中国航天科技集团",
                        "制造", "技术", "北京/西安/成都/酒泉", "12k-25k·14薪",
                        "硕士优先", "2027 届应届毕业生", TARGETED, LocalDate.of(2026, 11, 15),
                        "https://campus.spacechina.com/",
                        "航天科技集团专项引才，参与运载火箭、卫星、载人航天工程相关研制，事业编制待遇。",
                        "1. 航空航天/力学/电子/计算机相关专业硕士及以上优先；2. 政治可靠，通过保密审查；3. 立志航天事业。",
                        "定向,航天,国防,事业编制"),
                new JobDto("seed-multi-adbc-targeted", "专项招聘·乡村振兴金融专员计划", "中国农业发展银行",
                        "金融", "金融", "全国县域网点", "8k-14k·13薪",
                        "本科及以上", "2027 届应届毕业生", TARGETED, LocalDate.of(2026, 11, 20),
                        "https://job.adbc.com.cn/",
                        "农发行专项招聘，定向补充县域信贷与支农岗位，服务国家粮食安全与乡村振兴战略。",
                        "1. 2027 届全日制本科及以上，经济/金融/农学相关专业优先；2. 接受县域工作安排；3. 符合银行亲属回避规定。",
                        "定向,政策性银行,乡村振兴,编制"),
                new JobDto("seed-multi-szjy-targeted", "专项招聘·基础教育优才计划", "深圳市教育局",
                        "教育", "其他", "深圳各区", "18k-32k·13薪",
                        "硕士及以上", "2027 届应届毕业生", TARGETED, LocalDate.of(2026, 10, 20),
                        "http://szeb.sz.gov.cn/",
                        "深圳基础教育优才定向招聘，面向重点师范院校与综合大学优秀毕业生，编制+人才房政策。",
                        "1. 部属公费师范生或双一流硕士及以上；2. 持有对应学科教师资格证；3. 通过教育局统一考核。",
                        "定向,教师,编制,人才房"),
                new JobDto("seed-multi-crc-targeted", "专项招聘·高铁研发青苗计划", "中国中车",
                        "制造", "技术", "青岛/株洲/常州", "13k-24k·14薪",
                        "硕士优先", "2027 届应届毕业生", TARGETED, LocalDate.of(2026, 12, 10),
                        "https://zhaopin.crrcgc.cc/",
                        "中国中车青苗计划专项招聘，定向补充高铁动车组与城轨车辆研发核心团队，院士工作站培养。",
                        "1. 机械/电气/材料/软件相关专业硕士及以上优先；2. 有轨道交通项目经历者优先；3. 认同高端装备制造使命。",
                        "定向,高铁,高端制造,国企")
        );
    }
}
